### ISSUE TITLE
Args should be taken as lists instead of strings

### ISSUE THREAD

**Issue by SohamGhugare** [CodeWithSwastik/vscode-ext#14]
Make it so display functions should take in args as **lists** and not strings, so we can pass in complete lists instead of passing the individually  list values in the form of strings. 
Example: `vscode.window.show_info_message("Options", ['opt-1', 'opt-2', 'opt-3'])`

**Comment by CodeWithSwastik** [comment]
You could unpack the list before passing it like so 
```python
args = ['opt-1', 'opt-2', 'opt-3']
vscode.window.show_info_message("Options", *args)
```

**Comment by CodeWithSwastik** [comment]
However it does look better with lists so I'll consider adding that while still supporting the previous way of doing it.
