### ISSUE TITLE
Add more window API functions

### ISSUE THREAD

**Issue by CodeWithSwastik** [CodeWithSwastik/vscode-ext#8]

**Comment by nv2k3** [comment]
Hey how to open file in vscode,
```py
vscode.env.open_external(link)
```
using this or any other way

**Comment by CodeWithSwastik** [comment]
> Hey how to open file in vscode,
> 
> ```python
> vscode.env.open_external(link)
> ```
> 
> using this or any other way

You'll need to use [`vscode.window.show_text_document`](https://github.com/CodeWithSwastik/vscode-ext/blob/main/vscode/window.py#L165) which has been newly added to v1.5.3. This function takes in 2 parameters, the uri of the file and [`TextDocumentShowOptions`](https://github.com/CodeWithSwastik/vscode-ext/blob/main/vscode/types.py#L373)
